export const FRAME_WIDTH = 1512;
export const FRAME_HEIGHT = 982;
export const FOCAL_X = FRAME_WIDTH / 2;
export const WIDE_FRAME_WIDTH = 3840;
export const WIDE_FRAME_HEIGHT = 1080;
export const MAX_SCENE_ASPECT_RATIO = WIDE_FRAME_WIDTH / WIDE_FRAME_HEIGHT;
export const WIDE_FOCAL_X = WIDE_FRAME_WIDTH / 2;
export const CORE_ASPECT_RATIO = FRAME_WIDTH / FRAME_HEIGHT;
export const WIDE_TARGET_ASPECT_RATIO = WIDE_FRAME_WIDTH / WIDE_FRAME_HEIGHT;
export const WIDE_FRONT_SWAP_RATIO =
  CORE_ASPECT_RATIO + (WIDE_TARGET_ASPECT_RATIO - CORE_ASPECT_RATIO) * 0.7;
export const WIDE_WATER_SWAP_RATIO =
  CORE_ASPECT_RATIO + (WIDE_TARGET_ASPECT_RATIO - CORE_ASPECT_RATIO) * 0.95;
export const CORE_WATER_STACK_Z_INDEX = 4;
