import { resolvePhoto } from "./photos";
import type { TeamMember } from "./types";

export const teamMembers: Record<string, TeamMember> = {
  "shelf-1-jar-1": {
    id: "luna",
    name: "Luna Bertha",
    role: "Co-President",
    avatarSrc: resolvePhoto("luna"),
    linkedinUrl: "https://www.linkedin.com/in/lunabertha/",
  },
  "shelf-1-jar-2": {
    id: "shreyas",
    name: "Shreyas Rao",
    role: "Co-President",
    avatarSrc: resolvePhoto("shreyas"),
    linkedinUrl: "https://www.linkedin.com/in/shreyasrao14/",
  },
  "shelf-1-jar-3": {
    id: "conrad",
    name: "Conrad Mo",
    role: "Director of Development",
    avatarSrc: resolvePhoto("conrad"),
    linkedinUrl: "https://www.linkedin.com/in/conradmo/",
  },
  "shelf-1-jar-4": {
    id: "preston",
    name: "Preston Tom-Ying",
    role: "Web Developer",
    avatarSrc: resolvePhoto("preston"),
    linkedinUrl: "https://www.linkedin.com/in/prestonty/",
  },
  "shelf-1-jar-5": {
    id: "kate",
    name: "Kate Huang",
    role: "Web Developer",
    avatarSrc: resolvePhoto("kate"),
    linkedinUrl: "https://www.linkedin.com/in/katehuang-/",
  },
  "shelf-1-jar-6": {
    id: "samuel",
    name: "Samuel Tjhia",
    role: "Web Developer",
    avatarSrc: resolvePhoto("samuel"),
    linkedinUrl: "https://www.linkedin.com/in/samtjhia/",
  },
  "shelf-1-jar-7": {
    id: "karen",
    name: "Karen Lin",
    role: "Web Developer",
    avatarSrc: resolvePhoto("karen"),
    linkedinUrl: "https://www.linkedin.com/in/karenlin2026/",
  },
  "shelf-1-jar-8": {
    id: "andy",
    name: "Andy Yin",
    role: "Web Developer",
    avatarSrc: resolvePhoto("andy"),
    linkedinUrl: "https://www.linkedin.com/in/yin-andy/",
  },
  "shelf-1-jar-9": {
    id: "jinie",
    name: "Jinie Choi",
    role: "Director of Marketing and Design",
    avatarSrc: resolvePhoto("jinie"),
    linkedinUrl: "https://www.linkedin.com/in/emily-j-choi-/",
  },
  "shelf-1-jar-10": {
    id: "tony",
    name: "Tony Park",
    role: "Marketing Coordinator",
    avatarSrc: resolvePhoto("tony"),
    linkedinUrl: "https://www.linkedin.com/in/tyhp/",
  },
  "shelf-1-jar-11": {
    id: "amanda",
    name: "Amanda Zhu",
    role: "Marketing Coordinator",
    avatarSrc: resolvePhoto("amanda"),
    linkedinUrl: "https://www.linkedin.com/in/amandajzhu/",
  },
  "shelf-2-jar-1": {
    id: "jessica",
    name: "Jessica Ocampo",
    role: "Director of Design",
    avatarSrc: resolvePhoto("jessica"),
    linkedinUrl: "https://www.linkedin.com/in/jessica--ocampo/",
  },
  "shelf-2-jar-2": {
    id: "chavi",
    name: "Chavi Sharma",
    role: "UI/UX Designer",
    avatarSrc: resolvePhoto("chavi"),
    linkedinUrl: "https://www.linkedin.com/in/chavisharma7/",
  },
  "shelf-2-jar-3": {
    id: "joy",
    name: "Joy Wang",
    role: "UI/UX Designer",
    avatarSrc: resolvePhoto("joy"),
    linkedinUrl: "https://www.linkedin.com/in/joy-wang-a7475b325/",
  },
  "shelf-2-jar-4": {
    id: "sydney",
    name: "Sydney Bernal",
    role: "UI/UX Designer",
    avatarSrc: resolvePhoto("sydney"),
    linkedinUrl: "https://www.linkedin.com/in/svbernal/",
  },
  "shelf-2-jar-5": {
    id: "james",
    name: "James Liang",
    role: "Co-Director of Sponsorships",
    avatarSrc: resolvePhoto("james"),
    linkedinUrl: "https://www.linkedin.com/in/james-liang-/",
  },
  "shelf-2-jar-6": {
    id: "john",
    name: "John Xu",
    role: "Co-Director of Sponsorships",
    avatarSrc: resolvePhoto("john"),
    linkedinUrl: "https://www.linkedin.com/in/winghoxu/",
  },
  "shelf-2-jar-7": {
    id: "josephine",
    name: "Josephine Thjia",
    role: "Sponsorships Coordinator",
    avatarSrc: resolvePhoto("josephine"),
    linkedinUrl: "https://www.linkedin.com/in/josephine-tjhia/",
  },
  "shelf-2-jar-8": {
    id: "dorothy",
    name: "Dorothy Zheng",
    role: "Sponsorships Coordinator",
    avatarSrc: resolvePhoto("dorothy"),
    linkedinUrl: "https://www.linkedin.com/in/dorothy-zheng07/",
  },
  "shelf-2-jar-9": {
    id: "lawrence",
    name: "Lawrence Ing",
    role: "Sponsorships Coordinator",
    avatarSrc: resolvePhoto("lawrence"),
    linkedinUrl: "https://www.linkedin.com/in/lawrenceing/",
  },
  "shelf-2-jar-10": {
    id: "natasha",
    name: "Natasha Ejercito",
    role: "Sponsorships Coordinator",
    avatarSrc: resolvePhoto("natasha"),
    linkedinUrl: "https://www.linkedin.com/in/natashaejercito/",
  },
  "shelf-2-jar-11": {
    id: "ben",
    name: "Ben Zhou",
    role: "Sponsorships Coordinator",
    avatarSrc: resolvePhoto("ben"),
    linkedinUrl: "https://www.linkedin.com/in/-ben-zhou-",
  },
  "shelf-2-jar-12": {
    id: "peter",
    name: "Peter Lian",
    role: "Sponsorships Coordinator",
    avatarSrc: resolvePhoto("peter"),
    linkedinUrl: "https://www.linkedin.com/in/yishuolian/",
  },
  "shelf-2-jar-13": {
    id: "hibba",
    name: "Hibba Nouman",
    role: "Sponsorship Coordinator",
    avatarSrc: resolvePhoto("default"),
    linkedinUrl: "https://www.linkedin.com/in/hibba-nouman/",
  },
  "shelf-2-jar-14": {
    id: "danielle",
    name: "Danielle Santos",
    role: "Sponsorship Coordinator",
    avatarSrc: resolvePhoto("danielle"),
    linkedinUrl: "https://www.linkedin.com/in/danielle-andrea-santos-83974523a/",
  },
  "shelf-3-jar-1": {
    id: "johnson",
    name: "Johnson Jiang",
    role: "Director of Logistics",
    avatarSrc: resolvePhoto("johnson"),
    linkedinUrl: "https://www.linkedin.com/in/jjohnsonjiang/",
  },
  "shelf-3-jar-2": {
    id: "aran",
    name: "Aran Saseelan",
    role: "Logistics Coordinator",
    avatarSrc: resolvePhoto("aran"),
    linkedinUrl: "https://www.linkedin.com/in/aransaseelan/",
  },
  "shelf-3-jar-3": {
    id: "iris",
    name: "Iris Xie",
    role: "Logistics Coordinator",
    avatarSrc: resolvePhoto("iris"),
    linkedinUrl: "https://www.linkedin.com/in/iris-xie-a305aa364/",
  },
  "shelf-3-jar-4": {
    id: "isabelle",
    name: "Isabelle Xu",
    role: "Logistics and Marketing Coordinator",
    avatarSrc: resolvePhoto("isabelle"),
    linkedinUrl: "https://www.linkedin.com/in/isabellenaxu/",
  },
  "shelf-3-jar-5": {
    id: "rose",
    name: "Rose Gu",
    role: "Logistics Coordinator",
    avatarSrc: resolvePhoto("rose"),
    linkedinUrl: "https://www.linkedin.com/in/rose-luoyuan-gu-098270368/",
  },
  "shelf-3-jar-6": {
    id: "hillary",
    name: "Hillary Tse",
    role: "Director of Finance and Web Developer",
    avatarSrc: resolvePhoto("hillary"),
    linkedinUrl: "https://www.linkedin.com/in/tse-hillary/",
  },
  "shelf-3-jar-7": {
    id: "andrew",
    name: "Andrew Li",
    role: "Finance Coordinator",
    avatarSrc: resolvePhoto("andrew"),
    linkedinUrl: "https://www.linkedin.com/in/andrewyili/",
  },
};
