import { resolvePhoto } from "./photos";
import type { TeamMember } from "./types";

export const teamMembers: Record<string, TeamMember> = {
  "shelf-1-jar-1": {
    id: "luna",
    name: "Luna Bertha",
    role: "Co-President",
    avatarSrc: resolvePhoto("luna"),
  },
  "shelf-1-jar-2": {
    id: "shreyas",
    name: "Shreyas Rao",
    role: "Co-President",
    avatarSrc: resolvePhoto("shreyas"),
  },
  "shelf-1-jar-3": {
    id: "conrad",
    name: "Conrad Mo",
    role: "Director of Development",
    avatarSrc: resolvePhoto("conrad"),
  },
  "shelf-1-jar-4": {
    id: "preston",
    name: "Preston Tom-Ying",
    role: "Web Developer",
    avatarSrc: resolvePhoto("preston"),
  },
  "shelf-1-jar-5": {
    id: "kate",
    name: "Kate Huang",
    role: "Web Developer",
    avatarSrc: resolvePhoto("kate"),
  },
  "shelf-1-jar-6": {
    id: "samuel",
    name: "Samuel Tjhia",
    role: "Web Developer",
    avatarSrc: resolvePhoto("samuel"),
  },
  "shelf-1-jar-7": {
    id: "karen",
    name: "Karen Lin",
    role: "Web Developer",
    avatarSrc: resolvePhoto("karen"),
  },
  "shelf-1-jar-8": {
    id: "andy",
    name: "Andy Yin",
    role: "Web Developer",
    avatarSrc: resolvePhoto("andy"),
  },
  "shelf-1-jar-9": {
    id: "jinie",
    name: "Jinie Choi",
    role: "Director of Marketing and Design",
    avatarSrc: resolvePhoto("jinie"),
  },
  "shelf-1-jar-10": {
    id: "jessica",
    name: "Jessica Ocampo",
    role: "Director of Design",
    avatarSrc: resolvePhoto("jessica"),
  },
  "shelf-1-jar-11": {
    id: "amanda",
    name: "Amanda Zhu",
    role: "Marketing Coordinator",
    avatarSrc: resolvePhoto("amanda"),
  },
  "shelf-2-jar-1": {
    id: "tony",
    name: "Tony Park",
    role: "Marketing Coordinator",
    avatarSrc: resolvePhoto("tony"),
  },
  "shelf-2-jar-2": {
    id: "chavi",
    name: "Chavi Sharma",
    role: "UI/UX Designer",
    avatarSrc: resolvePhoto("chavi"),
  },
  "shelf-2-jar-3": {
    id: "joy",
    name: "Joy Wang",
    role: "UI/UX Designer",
    avatarSrc: resolvePhoto("joy"),
  },
  "shelf-2-jar-4": {
    id: "sydney",
    name: "Sydney Bernal",
    role: "UI/UX Designer",
    avatarSrc: resolvePhoto("sydney"),
  },
  "shelf-2-jar-5": {
    id: "james",
    name: "James Liang",
    role: "Co-Director of Sponsorships",
    avatarSrc: resolvePhoto("james"),
  },
  "shelf-2-jar-6": {
    id: "john",
    name: "John Xu",
    role: "Co-Director of Sponsorships",
    avatarSrc: resolvePhoto("john"),
  },
  "shelf-2-jar-7": {
    id: "josephine",
    name: "Josephine Thjia",
    role: "Sponsorships Coordinator",
    avatarSrc: resolvePhoto("josephine"),
  },
  "shelf-2-jar-8": {
    id: "dorothy",
    name: "Dorothy Zheng",
    role: "Sponsorships Coordinator",
    avatarSrc: resolvePhoto("dorothy"),
  },
  "shelf-2-jar-9": {
    id: "lawrence",
    name: "Lawrence Ing",
    role: "Sponsorships Coordinator",
    avatarSrc: resolvePhoto("lawrence"),
  },
  "shelf-2-jar-10": {
    id: "natasha",
    name: "Natasha Ejercito",
    role: "Sponsorships Coordinator",
    avatarSrc: resolvePhoto("natasha"),
  },
  "shelf-2-jar-11": {
    id: "ben",
    name: "Ben Zhou",
    role: "Sponsorships Coordinator",
    avatarSrc: resolvePhoto("ben"),
  },
  "shelf-2-jar-12": {
    id: "peter",
    name: "Peter Lian",
    role: "Sponsorships Coordinator",
    avatarSrc: resolvePhoto("peter"),
  },
  "shelf-2-jar-13": {
    id: "hibba",
    name: "Hibba Nouman",
    role: "Sponsorship Coordinator",
    avatarSrc: resolvePhoto("default"),
  },
  "shelf-2-jar-14": {
    id: "danielle",
    name: "Danielle Santos",
    role: "Sponsorship Coordinator",
    avatarSrc: resolvePhoto("default"),
  },
  "shelf-3-jar-1": {
    id: "johnson",
    name: "Johnson Jiang",
    role: "Director of Logistics",
    avatarSrc: resolvePhoto("johnson"),
  },
  "shelf-3-jar-2": {
    id: "aran",
    name: "Aran Saseelan",
    role: "Logistics Coordinator",
    avatarSrc: resolvePhoto("aran"),
  },
  "shelf-3-jar-3": {
    id: "iris",
    name: "Iris Xie",
    role: "Logistics Coordinator",
    avatarSrc: resolvePhoto("iris"),
  },
  "shelf-3-jar-4": {
    id: "isabelle",
    name: "Isabelle Xu",
    role: "Logistics and Marketing Coordinator",
    avatarSrc: resolvePhoto("isabelle"),
  },
  "shelf-3-jar-5": {
    id: "rose",
    name: "Rose Gu",
    role: "Logistics Coordinator",
    avatarSrc: resolvePhoto("rose"),
  },
  "shelf-3-jar-6": {
    id: "hillary",
    name: "Hillary Tse",
    role: "Director of Finance and Web Developer",
    avatarSrc: resolvePhoto("hillary"),
  },
  "shelf-3-jar-7": {
    id: "andrew",
    name: "Andrew Li",
    role: "Finance Coordinator",
    avatarSrc: resolvePhoto("andrew"),
  },
};
