export const COUNTRY_OPTIONS = [
  "Canada",
  "United States",
  "United Kingdom",
  "India",
  "Australia",
  "Germany",
  "France",
  "China",
  "Japan",
  "South Korea",
  "Brazil",
  "Mexico",
  "Italy",
  "Spain",
  "Russia",
  "South Africa",
  "New Zealand",
  "Netherlands",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Switzerland",
  "Turkey",
  "Saudi Arabia",
  "United Arab Emirates",
  "Singapore",
  "Malaysia",
  "Indonesia",
  "Thailand",
  "Vietnam",
  "Philippines",
  "Argentina",
  "Chile",
  "Colombia",
  "Egypt",
  "Nigeria",
  "Kenya",
  "Other",
];

export const SCHOOL_OPTIONS = [
  "Acadia University",
  "Algoma University",
  "Athabasca University",
  "Bishop's University",
  "Brandon University",
  "Brock University",
  "Cape Breton University",
  "Carleton University",
  "Concordia University",
  "Dalhousie University",
  "Emily Carr University of Art and Design",
  "First Nations University of Canada",
  "Kwantlen Polytechnic University",
  "Lakehead University",
  "Laval University",
  "Laurentian University",
  "MacEwan University",
  "McGill University",
  "McMaster University",
  "Memorial University of Newfoundland",
  "Mount Allison University",
  "Mount Royal University",
  "Mount Saint Vincent University",
  "Nipissing University",
  "NSCAD University",
  "OCAD University",
  "Ontario Tech University",
  "Polytechnique Montréal",
  "Queen's University",
  "Royal Military College of Canada",
  "Royal Roads University",
  "Saint Mary's University",
  "Simon Fraser University",
  "St. Francis Xavier University",
  "St. Thomas University",
  "Thompson Rivers University",
  "Toronto Metropolitan University",
  "Trent University",
  "University of Alberta",
  "University of British Columbia",
  "University of Calgary",
  "University of Guelph",
  "University of King's College",
  "University of Lethbridge",
  "University of Manitoba",
  "University of New Brunswick",
  "University of Northern British Columbia",
  "University of Ottawa",
  "University of Prince Edward Island",
  "University of Regina",
  "University of Saskatchewan",
  "University of Toronto (St. George)",
  "University of Toronto (Scarborough)",
  "University of Toronto (Mississauga)",
  "University of Victoria",
  "University of Waterloo",
  "University of Windsor",
  "University of Winnipeg",
  "Vancouver Island University",
  "Western University",
  "Wilfrid Laurier University",
  "York University",
  "Other",
];

export const MAJOR_OPTIONS = [
  "Computer Science",
  "Software Engineering",
  "Mechanical Engineering",
  "Electrical Engineering",
  "Civil Engineering",
  "Business Administration",
  "Accounting",
  "Finance",
  "Marketing",
  "Economics",
  "Biology",
  "Biotechnology",
  "Chemistry",
  "Physics",
  "Mathematics",
  "Statistics",
  "Psychology",
  "Sociology",
  "Political Science",
  "History",
  "Philosophy",
  "English Literature",
  "Education",
  "Environmental Science",
  "Nursing",
  "Medicine",
  "Law",
  "Architecture",
  "Fine Arts",
  "Music",
  "Theatre",
  "Other",
];

export const EDUCATION_LEVEL_OPTIONS = [
  "High School",
  "Freshman - Undergraduate",
  "Sophomore - Undergraduate",
  "Junior - Undergraduate",
  "Senior - Undergraduate",
  "Graduate",
  "PhD",
  "Other",
];

export const GENDER_OPTIONS = [
  "Male",
  "Female",
  "Non-binary",
  "Other",
  "Prefer not to say",
];

export const RACE_ETHNICITY_OPTIONS = [
  "Black/People of African Descent",
  "Arab/Middle Eastern",
  "East Asian (e.g. China, Japan, Korea)",
  "South/Southeast Asian (e.g. India, Pakistan, Sri Lanka, Philippines, Thailand)",
  "Indigenous Person of Canada",
  "Latinx",
  "West Asian (e.g. Iran, Afghanistan)",
  "White/People of European Descent",
  "Other",
  "Prefer not to say",
];
