export const COUNTRY_OPTIONS = [
  "Canada",
  "United States",
  "United Kingdom",
  "India",
  "Australia",
  "Germany",
  "France",
  "China",
  "Japan",
  "South Korea",
  "Brazil",
  "Mexico",
  "Italy",
  "Spain",
  "Russia",
  "South Africa",
  "New Zealand",
  "Netherlands",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Switzerland",
  "Turkey",
  "Saudi Arabia",
  "United Arab Emirates",
  "Singapore",
  "Malaysia",
  "Indonesia",
  "Thailand",
  "Vietnam",
  "Philippines",
  "Argentina",
  "Chile",
  "Colombia",
  "Egypt",
  "Nigeria",
  "Kenya",
  "Other",
];

export const SCHOOL_OPTIONS = [
  "Carleton University",
  "Concordia University",
  "Dalhousie University",
  "Laval University",
  "McGill University",
  "Memorial University of Newfoundland",
  "Queen's University",
  "Simon Fraser University",
  "Toronto Metropolitan University",
  "University of Alberta",
  "University of British Columbia",
  "University of Calgary",
  "University of Manitoba",
  "University of Ottawa",
  "University of Saskatchewan",
  "University of Toronto (St. George)",
  "University of Toronto (Scarborough)",
  "University of Toronto (Mississauga)",
  "University of Victoria",
  "University of Waterloo",
  "Western University",
  "York University",
  "Other",
];

export const MAJOR_OPTIONS = [
  "Computer Science",
  "Software Engineering",
  "Mechanical Engineering",
  "Electrical Engineering",
  "Civil Engineering",
  "Business Administration",
  "Accounting",
  "Finance",
  "Marketing",
  "Economics",
  "Biology",
  "Biotechnology",
  "Chemistry",
  "Physics",
  "Mathematics",
  "Statistics",
  "Psychology",
  "Sociology",
  "Political Science",
  "History",
  "Philosophy",
  "English Literature",
  "Education",
  "Environmental Science",
  "Nursing",
  "Medicine",
  "Law",
  "Architecture",
  "Fine Arts",
  "Music",
  "Theatre",
  "Other",
];

export const EDUCATION_LEVEL_OPTIONS = [
  "High School",
  "Freshman - Undergraduate",
  "Sophomore - Undergraduate",
  "Junior - Undergraduate",
  "Senior - Undergraduate",
  "Graduate",
  "PhD",
  "Other",
];

export const GENDER_OPTIONS = [
  "Male",
  "Female",
  "Non-binary",
  "Other",
  "Prefer not to say",
];

export const RACE_ETHNICITY_OPTIONS = [
  "Black/People of African Descent",
  "Arab/Middle Eastern",
  "East Asian (e.g. China, Japan, Korea)",
  "South/Southeast Asian (e.g. India, Pakistan, Sri Lanka, Philippines, Thailand)",
  "Indigenous Person of Canada",
  "Latinx",
  "West Asian (e.g. Iran, Afghanistan)",
  "White/People of European Descent",
  "Other",
  "Prefer not to say",
];
